import { MediaItem, MediaDetail } from './types';

export const MOCK_TRENDING: MediaItem[] = [
  {
    id: 94605,
    title: 'Arcane',
    original_title: 'Arcane: League of Legends',
    overview: 'Mitt i den skarpa konflikten mellan städerna Piltover och Zaun kämpar två systrar på motsatta sidor i ett krig mellan magiska teknologier och oförenliga övertygelser.',
    poster_path: '/abf8tHznhSvl9an90mi4ZCG0FHN.jpg',
    backdrop_path: '/7hqYs98B682N6nZ9Y4x16V13xS9.jpg',
    media_type: 'tv',
    first_air_date: '2021-11-06',
    vote_average: 8.8,
    vote_count: 4200,
    genre_ids: [16, 10765, 18],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    original_title: 'Dune: Part Two',
    overview: 'Följ Paul Atreides mytiska resa när han förenas med Chani och fremenerna medan han söker hämnd mot konspiratörerna som förstörde hans familj.',
    poster_path: '/czembW0Rk1Ke7lCJGzyAi8Fscgt.jpg',
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5200bm.jpg',
    media_type: 'movie',
    release_date: '2024-02-27',
    vote_average: 8.2,
    vote_count: 5800,
    genre_ids: [878, 12],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 126308,
    title: 'Shōgun',
    original_title: 'Shōgun',
    overview: 'I Japan år 1600 kämpar Lord Yoshii Toranaga för sitt liv när hans fiender på regentrådet enas mot honom, samtidigt som ett mystiskt europeiskt skepp strandsätts vid en närliggande fiskeby.',
    poster_path: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdrop_path: '/5zmiBoMzeWKVyr3v7usZ26U8c7i.jpg',
    media_type: 'tv',
    first_air_date: '2024-02-27',
    vote_average: 8.5,
    vote_count: 1400,
    genre_ids: [18, 10768],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 87108,
    title: 'Chernobyl',
    original_title: 'Chernobyl',
    overview: 'I april 1986 exploderar reaktor 4 i kärnkraftverket i Tjernobyl i Ukraina, vilket utlöser en av de värsta människoskapade katastroferna i historien.',
    poster_path: '/hlLXt2tOPT6RRnjiUmoxyG9LTFi.jpg',
    backdrop_path: '/uL6Ad12W0bxyH440b8qK0Z3U8sE.jpg',
    media_type: 'tv',
    first_air_date: '2019-05-06',
    vote_average: 8.9,
    vote_count: 6500,
    genre_ids: [18],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 1399,
    title: 'Game of Thrones',
    original_title: 'Game of Thrones',
    overview: 'Sju adelsfamiljer kämpar om kontrollen över det mytomspunna landet Westeros. Friktion mellan husen leder till fullskaligt krig.',
    poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    media_type: 'tv',
    first_air_date: '2011-04-17',
    vote_average: 8.4,
    vote_count: 24500,
    genre_ids: [10765, 18, 10759],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    overview: 'Historien om den amerikanske vetenskapsmannen J. Robert Oppenheimer och hans roll i utvecklingen av atombomben under Manhattanprojektet.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/rLb2cw0iwOadbJ9flEjUTmqzgDJ.jpg',
    media_type: 'movie',
    release_date: '2023-07-19',
    vote_average: 8.1,
    vote_count: 9100,
    genre_ids: [18, 36],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 119051,
    title: 'Wednesday',
    original_title: 'Wednesday',
    overview: 'En smart, sarkastisk och något död inombords Wednesday Addams undersöker en mordvåg samtidigt som hon skaffar nya vänner och fiender på Nevermore Academy.',
    poster_path: '/9PFonQ95165agq935iUjhkEjxUt.jpg',
    backdrop_path: '/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg',
    media_type: 'tv',
    first_air_date: '2022-11-23',
    vote_average: 8.3,
    vote_count: 8500,
    genre_ids: [10765, 9648, 35],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 100088,
    title: 'The Last of Us',
    original_title: 'The Last of Us',
    overview: '20 år efter att en svampinfektion utplånat civilisationen anlitas den härdade överlevaren Joel för att smuggla 14-åriga Ellie ut ur en förtryckande karantänzon.',
    poster_path: '/uKvVjK19szUZRsUtraFXvgvgNxD.jpg',
    backdrop_path: '/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    media_type: 'tv',
    first_air_date: '2023-01-15',
    vote_average: 8.6,
    vote_count: 5300,
    genre_ids: [18, 10765, 10759],
    origin_country: ['US'],
    original_language: 'en',
  },
  {
    id: 95557,
    title: 'Young Royals',
    original_title: 'Young Royals',
    overview: 'Prins Wilhelm anpassar sig till livet på den prestigefyllda internatskolan Hillerska, men att följa sitt hjärta visar sig vara svårare än han trott.',
    poster_path: '/iZ2o7iW5UqV17kH8f888B2Uv0K.jpg',
    backdrop_path: '/u6lKz3r2TzP5qH7G7P4w11YqH.jpg',
    media_type: 'tv',
    first_air_date: '2021-07-01',
    vote_average: 8.5,
    vote_count: 980,
    genre_ids: [18],
    origin_country: ['SE'],
    original_language: 'sv',
  },
  {
    id: 157336,
    title: 'Interstellar',
    original_title: 'Interstellar',
    overview: 'I en framtid där jorden plågas av torka och svält reser en grupp astronauter genom ett maskhål nära Saturnus i jakt på ett nytt hem för mänskligheten.',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    media_type: 'movie',
    release_date: '2014-11-05',
    vote_average: 8.4,
    vote_count: 36000,
    genre_ids: [12, 18, 878],
    origin_country: ['US'],
    original_language: 'en',
  }
];

export const MOCK_GENRES = [
  { id: 28, name: 'Action' },
  { id: 12, name: 'Äventyr' },
  { id: 16, name: 'Animering' },
  { id: 35, name: 'Komedi' },
  { id: 80, name: 'Kriminalare' },
  { id: 99, name: 'Dokumentär' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Familj' },
  { id: 14, name: 'Fantasy' },
  { id: 36, name: 'Historia' },
  { id: 27, name: 'Skräck' },
  { id: 10402, name: 'Musik' },
  { id: 9648, name: 'Mysterium' },
  { id: 10749, name: 'Romantik' },
  { id: 878, name: 'Sci-Fi' },
  { id: 53, name: 'Thriller' },
  { id: 10752, name: 'Krig' },
  { id: 10765, name: 'Sci-Fi & Fantasy' },
  { id: 10759, name: 'Action & Äventyr' },
];

export const MOCK_DETAILS: Record<number, MediaDetail> = {
  94605: {
    id: 94605,
    title: 'Arcane',
    original_title: 'Arcane: League of Legends',
    overview: 'Mitt i den skarpa konflikten mellan städerna Piltover och Zaun kämpar två systrar på motsatta sidor i ett krig mellan magiska teknologier och oförenliga övertygelser.',
    tagline: 'Vissa band kan aldrig brytas.',
    poster_path: '/abf8tHznhSvl9an90mi4ZCG0FHN.jpg',
    backdrop_path: '/7hqYs98B682N6nZ9Y4x16V13xS9.jpg',
    media_type: 'tv',
    first_air_date: '2021-11-06',
    status: 'Returning Series',
    vote_average: 8.8,
    vote_count: 4200,
    number_of_seasons: 2,
    number_of_episodes: 18,
    genres: [{ id: 16, name: 'Animering' }, { id: 10765, name: 'Sci-Fi & Fantasy' }, { id: 18, name: 'Drama' }],
    origin_country: ['US'],
    seasons: [
      {
        id: 134187,
        season_number: 1,
        name: 'Säsong 1',
        overview: 'Systrarna Vi och Powder testas till gränsen i Piltovers undre värld.',
        poster_path: '/abf8tHznhSvl9an90mi4ZCG0FHN.jpg',
        air_date: '2021-11-06',
        episode_count: 9,
        episodes: [
          { id: 1, season_number: 1, episode_number: 1, name: 'Välkommen till lekplatsen', overview: 'De föräldralösa systrarna Vi och Powder leder ett inbrott i ett laboratorium i Piltover.', air_date: '2021-11-06', still_path: '/nTv6n2qYVwA4Q3k2pW4L1K7zY1.jpg', vote_average: 8.4, runtime: 43 },
          { id: 2, season_number: 1, episode_number: 2, name: 'En del mysterier är bäst olösta', overview: 'Den idealistiske forskaren Jayce riskerar sin framtid genom olaglig forskning.', air_date: '2021-11-06', still_path: '/x7mYw4K1r5k0K2zT7b6m9Q1K4.jpg', vote_average: 8.5, runtime: 41 },
          { id: 3, season_number: 1, episode_number: 3, name: 'Grundläggande våld som krävs för förändring', overview: 'En episk konfrontation förändrar relationen mellan systrarna för alltid.', air_date: '2021-11-06', still_path: '/b4K9m1n0r7Q2w3K6m1p4v8X1L.jpg', vote_average: 9.3, runtime: 44 },
          { id: 4, season_number: 1, episode_number: 4, name: 'Glada Framstegens Dag!', overview: 'Flera år senare firar Piltover teknologisk dominans medan Zauns mörker växer.', air_date: '2021-11-13', still_path: null, vote_average: 8.6, runtime: 40 },
          { id: 5, season_number: 1, episode_number: 5, name: 'Alla vill vara min fiende', overview: 'Caitlyn söker ledtrådar i Zaun med hjälp av en osannolik allierad.', air_date: '2021-11-13', still_path: null, vote_average: 8.7, runtime: 40 },
          { id: 6, season_number: 1, episode_number: 6, name: 'När dessa murar faller', overview: 'Återföreningar och svek i skuggorna av Piltovers höjder.', air_date: '2021-11-13', still_path: null, vote_average: 9.0, runtime: 42 },
          { id: 7, season_number: 1, episode_number: 7, name: 'Pojkfrälsaren', overview: 'Ekko visar Vi en plats hon aldrig trodde kunde existera.', air_date: '2021-11-20', still_path: null, vote_average: 8.9, runtime: 40 },
          { id: 8, season_number: 1, episode_number: 8, name: 'Olja och vatten', overview: 'Mel och rådet tvingas fatta ett avgörande politiskt beslut.', air_date: '2021-11-20', still_path: null, vote_average: 8.8, runtime: 40 },
          { id: 9, season_number: 1, episode_number: 9, name: 'Monstret du skapade', overview: 'Den våldsamma säsongsfinalen där framtiden för två städer avgörs.', air_date: '2021-11-20', still_path: null, vote_average: 9.5, runtime: 41 },
        ]
      },
      {
        id: 284190,
        season_number: 2,
        name: 'Säsong 2',
        overview: 'Efterdyningarna av attacken mot rådet ställer systrarna inför det slutgiltiga ödet.',
        poster_path: '/7hqYs98B682N6nZ9Y4x16V13xS9.jpg',
        air_date: '2024-11-09',
        episode_count: 9,
        episodes: [
          { id: 10, season_number: 2, episode_number: 1, name: 'Tung är kronan', overview: 'Piltover rustar för hämnd medan Zaun delas i kaos.', air_date: '2024-11-09', still_path: null, vote_average: 8.9, runtime: 43 },
          { id: 11, season_number: 2, episode_number: 2, name: 'Se hur allt brinner', overview: 'Jinx flyr genom tunnlarna när Enforcers slår till med full kraft.', air_date: '2024-11-09', still_path: null, vote_average: 9.0, runtime: 44 },
          { id: 12, season_number: 2, episode_number: 3, name: 'Slutpunkten', overview: 'Ett oväntat möte kastar tvivel över alla gamla allianser.', air_date: '2024-11-09', still_path: null, vote_average: 9.2, runtime: 45 },
          { id: 13, season_number: 2, episode_number: 4, name: 'Målaren', overview: 'Ett nytt perspektiv på det förflutna visar vägen framåt.', air_date: '2024-11-16', still_path: null, vote_average: 8.7, runtime: 42 },
          { id: 14, season_number: 2, episode_number: 5, name: 'Blod och järn', overview: 'Krigets brutalitet drabbar oskyldiga på båda sidor.', air_date: '2024-11-16', still_path: null, vote_average: 8.9, runtime: 41 },
          { id: 15, season_number: 2, episode_number: 6, name: 'Budbäraren', overview: 'En hemlig sanning om Hextech uppdagas.', air_date: '2024-11-16', still_path: null, vote_average: 9.1, runtime: 44 },
          { id: 16, season_number: 2, episode_number: 7, name: 'Skärvor', overview: 'Det sista försvaret samlas inför avgörandet.', air_date: '2024-11-23', still_path: null, vote_average: 8.8, runtime: 43 },
          { id: 17, season_number: 2, episode_number: 8, name: 'Eko av det förflutna', overview: 'Slaget når hjärtat av Piltover.', air_date: '2024-11-23', still_path: null, vote_average: 9.3, runtime: 46 },
          { id: 18, season_number: 2, episode_number: 9, name: 'Slutet på en era', overview: 'Den monumentala finalen i Arcane-sagan.', air_date: '2024-11-23', still_path: null, vote_average: 9.6, runtime: 48 },
        ]
      }
    ]
  },
  693134: {
    id: 693134,
    title: 'Dune: Part Two',
    original_title: 'Dune: Part Two',
    overview: 'Följ Paul Atreides mytiska resa när han förenas med Chani och fremenerna medan han söker hämnd mot konspiratörerna som förstörde hans familj. Inför ett val mellan sitt livs kärlek och det kända universums öde försöker han förhindra en fruktansvärd framtid som bara han kan förutse.',
    tagline: 'Länge leve kämparna.',
    poster_path: '/czembW0Rk1Ke7lCJGzyAi8Fscgt.jpg',
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5200bm.jpg',
    media_type: 'movie',
    release_date: '2024-02-27',
    runtime: 166,
    status: 'Released',
    vote_average: 8.2,
    vote_count: 5800,
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 12, name: 'Äventyr' }],
    origin_country: ['US'],
    credits: {
      cast: [
        { id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profile_path: '/BE2sdjpgsa2rNTFa66f7upkaOP.jpg' },
        { id: 505710, name: 'Zendaya', character: 'Chani', profile_path: '/r2J00Wj60t73e9e1eK3K9zP.jpg' },
        { id: 93502, name: 'Rebecca Ferguson', character: 'Lady Jessica Atreides', profile_path: '/6NRi2sEaFqK4o2L3P6x7yZ.jpg' },
        { id: 74568, name: 'Javier Bardem', character: 'Stilgar', profile_path: '/g3tMvL0YnF8kX5K9pQ.jpg' },
      ]
    }
  },
  126308: {
    id: 126308,
    title: 'Shōgun',
    original_title: 'Shōgun',
    overview: 'I Japan år 1600 kämpar Lord Yoshii Toranaga för sitt liv när hans fiender på regentrådet enas mot honom, samtidigt som ett mystiskt europeiskt skepp strandsätts vid en närliggande fiskeby.',
    tagline: 'Ödet är inte något du väljer.',
    poster_path: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdrop_path: '/5zmiBoMzeWKVyr3v7usZ26U8c7i.jpg',
    media_type: 'tv',
    first_air_date: '2024-02-27',
    status: 'Returning Series',
    vote_average: 8.5,
    vote_count: 1400,
    number_of_seasons: 1,
    number_of_episodes: 10,
    genres: [{ id: 18, name: 'Drama' }, { id: 10768, name: 'Krig & Politik' }],
    origin_country: ['US'],
    seasons: [
      {
        id: 201123,
        season_number: 1,
        name: 'Säsong 1',
        overview: 'Toranagas uppgång i ett feodalt Japan på gränsen till inbördeskrig.',
        poster_path: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
        air_date: '2024-02-27',
        episode_count: 10,
        episodes: [
          { id: 101, season_number: 1, episode_number: 1, name: 'Kapitel ett: Anjin', overview: 'Ett holländskt handelsskepp når Japans kust med engelsmannen John Blackthorne ombord.', air_date: '2024-02-27', still_path: null, vote_average: 8.3, runtime: 68 },
          { id: 102, season_number: 1, episode_number: 2, name: 'Kapitel två: Tjänare till två herrar', overview: 'Blackthornes ankomst till Osaka orsakar oro hos de katolska jesuiter och regentrådet.', air_date: '2024-02-27', still_path: null, vote_average: 8.4, runtime: 58 },
          { id: 103, season_number: 1, episode_number: 3, name: 'Kapitel tre: Morgonens dröm', overview: 'Toranaga planerar en flykt från Osaka med Blackthornes hjälp.', air_date: '2024-03-05', still_path: null, vote_average: 8.6, runtime: 56 },
          { id: 104, season_number: 1, episode_number: 4, name: 'Kapitel fyra: Åtta-faldigt staket', overview: 'Blackthorne och Mariko etablerar ett band i Ajiro medan träningen av Toranagas trupper påbörjas.', air_date: '2024-03-12', still_path: null, vote_average: 8.7, runtime: 59 },
          { id: 105, season_number: 1, episode_number: 5, name: 'Kapitel fem: Trasiga nävar', overview: 'Ett jordskalv skakar regionen och testar lojaliteter.', air_date: '2024-03-19', still_path: null, vote_average: 8.5, runtime: 57 },
          { id: 106, season_number: 1, episode_number: 6, name: 'Kapitel sex: Kvinna av pilarna', overview: 'Marikos förflutna uppdagas och Toranagas strategi sätts på prov.', air_date: '2024-03-26', still_path: null, vote_average: 8.6, runtime: 55 },
          { id: 107, season_number: 1, episode_number: 7, name: 'Kapitel sju: Ett gungande träd', overview: 'Toranagas bror Saeki anländer med ett förslag från regentrådet.', air_date: '2024-04-02', still_path: null, vote_average: 8.8, runtime: 58 },
          { id: 108, season_number: 1, episode_number: 8, name: 'Kapitel åtta: Djupets lugn', overview: 'Toranaga kapitulerar till synes medan Mariko skickas på ett livsfarligt uppdrag till Osaka.', air_date: '2024-04-09', still_path: null, vote_average: 9.3, runtime: 60 },
          { id: 109, season_number: 1, episode_number: 9, name: 'Kapitel nio: Röd himmel', overview: 'Mariko konfronterar Ishido i Osaka i en dramatisk viljornas kamp.', air_date: '2024-04-16', still_path: null, vote_average: 9.6, runtime: 61 },
          { id: 110, season_number: 1, episode_number: 10, name: 'Kapitel tio: En dröm om en dröm', overview: 'Efterspelet av händelserna i Osaka banar väg för slaget vid Sekigahara.', air_date: '2024-04-23', still_path: null, vote_average: 9.2, runtime: 65 },
        ]
      }
    ]
  }
};
